# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 34ab53425b43ebc513b80ad5f3173df4d07704542824f5ac644d35c742e834906f4894fa106d6fb2f619794845fca98e6246494307d5b28f715b4da8db04e9c8

test:
  secret_key_base: ec1ea4449f35e41cd2bcca339a617063ede8a6a22d50fd85dbfff22165d82efbc3549502740934bb0f6e9c64238f0c7053ab55b17b5f33f8e27f0a65d1e5739e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
